### ISSUE TITLE
Adapter startet nicht

### ISSUE THREAD

**Issue by mrjeschke** [ioBroker/ioBroker.opcua#17]
Adapter läuft leider nicht.

Admin	v6.14.1
js-controller	5.0.19
Nodejs	v18.19.1
npm		10.2.4
opcua	v1.0.2
Debian Bullseye
`
2024-02-22 09:35:08.733 - error: host.opcua Caught by controller[0]: node:internal/modules/cjs/loader:1137
--
2024-02-22 09:35:08.733 - error: host.opcua Caught by controller[0]: throw err;
2024-02-22 09:35:08.733 - error: host.opcua Caught by controller[0]: ^
2024-02-22 09:35:08.733 - error: host.opcua Caught by controller[0]: Error: Cannot find module './lib/checkLicense'
2024-02-22 09:35:08.734 - error: host.opcua Caught by controller[0]: Require stack:
2024-02-22 09:35:08.734 - error: host.opcua Caught by controller[0]: - /opt/iobroker/node_modules/iobroker.opcua/main.js
2024-02-22 09:35:08.734 - error: host.opcua Caught by controller[0]: at Module._resolveFilename (node:internal/modules/cjs/loader:1134:15)
2024-02-22 09:35:08.734 - error: host.opcua Caught by controller[0]: at Module._load (node:internal/modules/cjs/loader:975:27)
2024-02-22 09:35:08.734 - error: host.opcua Caught by controller[0]: at Module.require (node:internal/modules/cjs/loader:1225:19)
2024-02-22 09:35:08.734 - error: host.opcua Caught by controller[0]: at require (node:internal/modules/helpers:177:18)
2024-02-22 09:35:08.734 - error: host.opcua Caught by controller[0]: at Object. (/opt/iobroker/node_modules/iobroker.opcua/main.js:14:22)
2024-02-22 09:35:08.734 - error: host.opcua Caught by controller[0]: at Module._compile (node:internal/modules/cjs/loader:1356:14)
2024-02-22 09:35:08.734 - error: host.opcua Caught by controller[0]: at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)
2024-02-22 09:35:08.734 - error: host.opcua Caught by controller[0]: at Module.load (node:internal/modules/cjs/loader:1197:32)
2024-02-22 09:35:08.734 - error: host.opcua Caught by controller[0]: at Module._load (node:internal/modules/cjs/loader:1013:12)
2024-02-22 09:35:08.734 - error: host.opcua Caught by controller[0]: at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:128:12) {
2024-02-22 09:35:08.734 - error: host.opcua Caught by controller[0]: code: 'MODULE_NOT_FOUND',
2024-02-22 09:35:08.734 - error: host.opcua Caught by controller[0]: requireStack: [ '/opt/iobroker/node_modules/iobroker.opcua/main.js' ]
2024-02-22 09:35:08.734 - error: host.opcua Caught by controller[0]: }
2024-02-22 09:35:08.734 - error: host.opcua Caught by controller[1]: Node.js v18.19.1
2024-02-22 09:35:08.734 - error: host.opcua instance system.adapter.opcua.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
`

**Comment by Matzeb15** [comment]
Hallo, bei mir kommen die selben Meldungen. Was mir dazu aufgefallen ist, war eine Warnung "The adapter seems to be compiled with a different Nodejs Version".
Habe jetzt nicht den genauen Wortlaut zur Hand aber muss hier eventuell der Adapter bei der Installation neu compiliert werden?

**Comment by Apollon77** [comment]
Nein das ist ein Fehler bitte letzte Version nutzen

**Comment by Matzeb15** [comment]
Die aktuelle Version ist die 1.0.2!? Diese habe ich zumindest installiert. 

Wenn ich den Adapter deinstalliere, Konsole oder auch im Admin mehrmals versucht, wird auch der Ordner `/opt/iobroker/node_modules/iobroker.opcua` entfernt. Bei Neuinstallation werden der Ordner neu angelegt und im Admin wird eine Instanz neu angelegt. Wenn ich den Adapter starte kommen folgende Fehlermeldungen.

Es wird auch der S7 Adapter neu gestartet. Die Steuerung, eine S7-1513, läuft aber ohne Fehlermeldungen weiter. Daran liegt es nicht.

> host.ioBroker
	2024-02-26 12:59:16.030	warn	instance system.adapter.s7.0 terminated due to SIGSEGV
host.ioBroker
	2024-02-26 12:59:11.424	warn	adapter "opcua" seems to be installed for a different version of Node.js. Trying to rebuild it... 1 attempt
host.ioBroker
	2024-02-26 12:59:11.423	error	instance system.adapter.opcua.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
host.ioBroker
	2024-02-26 12:59:11.423	error	Caught by controller[0]: Node.js v18.19.1
host.ioBroker
	2024-02-26 12:59:11.423	error	Caught by controller[0]: }
host.ioBroker
	2024-02-26 12:59:11.423	error	Caught by controller[0]: requireStack: [ '/opt/iobroker/node_modules/iobroker.opcua/main.js' ]
host.ioBroker
	2024-02-26 12:59:11.423	error	Caught by controller[0]: code: 'MODULE_NOT_FOUND',
host.ioBroker
	2024-02-26 12:59:11.423	error	Caught by controller[0]: at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:128:12) {
host.ioBroker
	2024-02-26 12:59:11.423	error	Caught by controller[0]: at Module._load (node:internal/modules/cjs/loader:1013:12)
host.ioBroker
	2024-02-26 12:59:11.423	error	Caught by controller[0]: at Module.load (node:internal/modules/cjs/loader:1197:32)
host.ioBroker
	2024-02-26 12:59:11.423	error	Caught by controller[0]: at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)
host.ioBroker
	2024-02-26 12:59:11.423	error	Caught by controller[0]: at Module._compile (node:internal/modules/cjs/loader:1356:14)
host.ioBroker
	2024-02-26 12:59:11.423	error	Caught by controller[0]: at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.opcua/main.js:14:22)
host.ioBroker
	2024-02-26 12:59:11.423	error	Caught by controller[0]: at require (node:internal/modules/helpers:177:18)
host.ioBroker
	2024-02-26 12:59:11.423	error	Caught by controller[0]: at Module.require (node:internal/modules/cjs/loader:1225:19)
host.ioBroker
	2024-02-26 12:59:11.423	error	Caught by controller[0]: at Module._load (node:internal/modules/cjs/loader:975:27)
host.ioBroker
	2024-02-26 12:59:11.423	error	Caught by controller[0]: at Module._resolveFilename (node:internal/modules/cjs/loader:1134:15)
host.ioBroker
	2024-02-26 12:59:11.423	error	Caught by controller[0]: - /opt/iobroker/node_modules/iobroker.opcua/main.js
host.ioBroker
	2024-02-26 12:59:11.423	error	Caught by controller[0]: Require stack:
host.ioBroker
	2024-02-26 12:59:11.423	error	Caught by controller[0]: Error: Cannot find module './lib/checkLicense'
host.ioBroker
	2024-02-26 12:59:11.423	error	Caught by controller[0]: ^
host.ioBroker
	2024-02-26 12:59:11.423	error	Caught by controller[0]: throw err;
host.ioBroker
	2024-02-26 12:59:11.423	error	Caught by controller[0]: node:internal/modules/cjs/loader:1137

**Comment by Matzeb15** [comment]
Kann es sein, dass hier Altlasten im System vorhanden sind die ich nicht ordnungsgemäß deinstalliere? Wo müsste ich nachschauen ob der Adapter wirklich restlos deinstalliert wurde?

**Comment by mrjeschke** [comment]
Ok, v1.0.3 läuft bei mir.

**Comment by Matzeb15** [comment]
Ja, die Version 1.0.3 funktioniert bei mir ebenfalls.

Vielen Dank
