### ISSUE TITLE
OPCUA Instanz Startet nicht

### ISSUE THREAD

**Issue by elektrofreak1986** [ioBroker/ioBroker.opcua#9]
Hallo,

ich würde gerne eine Anwendung mittels OPC UA mit Daten aus dem IOBroker füttern, leider bekomme ich den OPC UA Adapter nicht zum laufen, wollte es gerne testen.
In der Instanz öffnet sich der Register Server nicht.
Hat jemand erfahrung damit. Bin sehr interssiert an dem Adapter.

Gruß Sven

![1679777578309-optionen](https://user-images.githubusercontent.com/128969468/227770346-17a375b8-c654-4af1-84bb-7a4473057769.png)
![1679777593554-server](https://user-images.githubusercontent.com/128969468/227770350-504d6cba-66a1-4191-be71-8104a794bc63.png)

````
2023-03-25 21:22:13.486 - info: host.iobroker instance system.adapter.opcua.0 started with pid 2911
2023-03-25 21:22:14.045 - info: opcua.0 (2911) starting. Version 0.4.5 in /opt/iobroker/node_modules/iobroker.opcua, node: v16.19.1, js-controller: 4.0.24
2023-03-25 21:22:14.066 - error: opcua.0 (2911) No license found
2023-03-25 21:22:14.067 - warn: opcua.0 (2911) Only 10 data points allowed. To get support for more data points, please buy license under https://iobroker.net/accountLicenses
2023-03-25 21:22:14.130 - info: opcua.0 (2911) Published 0 states
2023-03-25 21:22:14.695 - error: opcua.0 (2911) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2023-03-25 21:22:14.695 - error: opcua.0 (2911) unhandled promise rejection: Cannot read properties of undefined (reading 'addressSpace')
2023-03-25 21:22:14.696 - error: opcua.0 (2911) TypeError: Cannot read properties of undefined (reading 'addressSpace')
at _0x56683e (/opt/iobroker/node_modules/iobroker.opcua/main.js:1:31499)
at /opt/iobroker/node_modules/node-opcua-server/dist/opcua_server.js:689:13
2023-03-25 21:22:14.696 - error: opcua.0 (2911) Cannot read properties of undefined (reading 'addressSpace')
2023-03-25 21:22:15.198 - info: opcua.0 (2911) terminating
2023-03-25 21:22:15.199 - warn: opcua.0 (2911) Terminated (UNCAUGHT_EXCEPTION): Without reason
2023-03-25 21:22:15.742 - error: host.iobroker instance system.adapter.opcua.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2023-03-25 21:22:15.742 - info: host.iobroker Restart adapter system.adapter.opcua.0 because enabled
2023-03-25 21:22:45.772 - info: host.iobroker instance system.adapter.opcua.0 started with pid 2926
2023-03-25 21:22:46.299 - info: opcua.0 (2926) starting. Version 0.4.5 in /opt/iobroker/node_modules/iobroker.opcua, node: v16.19.1, js-controller: 4.0.24
2023-03-25 21:22:46.318 - error: opcua.0 (2926) No license found
2023-03-25 21:22:46.318 - warn: opcua.0 (2926) Only 10 data points allowed. To get support for more data points, please buy license under https://iobroker.net/accountLicenses
2023-03-25 21:22:46.378 - info: opcua.0 (2926) Published 0 states
2023-03-25 21:22:46.920 - error: opcua.0 (2926) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2023-03-25 21:22:46.921 - error: opcua.0 (2926) unhandled promise rejection: Cannot read properties of undefined (reading 'addressSpace')
2023-03-25 21:22:46.921 - error: opcua.0 (2926) TypeError: Cannot read properties of undefined (reading 'addressSpace')
at _0x56683e (/opt/iobroker/node_modules/iobroker.opcua/main.js:1:31499)
at /opt/iobroker/node_modules/node-opcua-server/dist/opcua_server.js:689:13
2023-03-25 21:22:46.921 - error: opcua.0 (2926) Cannot read properties of undefined (reading 'addressSpace')
2023-03-25 21:22:47.424 - info: opcua.0 (2926) terminating
2023-03-25 21:22:47.425 - warn: opcua.0 (2926) Terminated (UNCAUGHT_EXCEPTION): Without reason
2023-03-25 21:22:47.966 - error: host.iobroker instance system.adapter.opcua.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2023-03-25 21:22:47.966 - info: host.iobroker Restart adapter system.adapter.opcua.0 because enabled
````

**Comment by artur-bw** [comment]
Es fehlt die OPC UA Server URL z.B.:
opc.tcp://192.168.44.2:4840
![image](https://github.com/ioBroker/ioBroker.opcua/assets/39700218/05a056ab-8c56-45b7-a14c-0eaea7e55699)

**Comment by GermanBluefox** [comment]
Please retest with 1.0.4
